// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4_Gd-cIa21JQUSHGJlN5CZnIIQ_2oFzQ',
    appId: '1:950594753791:web:290e398973c212050428ca',
    messagingSenderId: '950594753791',
    projectId: 'sih-weighing-verification',
    authDomain: 'sih-weighing-verification.firebaseapp.com',
    storageBucket: 'sih-weighing-verification.firebasestorage.app',
    measurementId: 'G-K6XZ8QZJEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFbk0qc9d8PqObHjm_3LEDKoKND1RYDnQ',
    appId: '1:950594753791:android:5682265fa73a9ee40428ca',
    messagingSenderId: '950594753791',
    projectId: 'sih-weighing-verification',
    storageBucket: 'sih-weighing-verification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzZqlZFLcg_MVUWh1WSIqA85aZjDG12yM',
    appId: '1:950594753791:ios:ed743e7c41acd0690428ca',
    messagingSenderId: '950594753791',
    projectId: 'sih-weighing-verification',
    storageBucket: 'sih-weighing-verification.firebasestorage.app',
    iosBundleId: 'com.example.ownerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzZqlZFLcg_MVUWh1WSIqA85aZjDG12yM',
    appId: '1:950594753791:ios:ed743e7c41acd0690428ca',
    messagingSenderId: '950594753791',
    projectId: 'sih-weighing-verification',
    storageBucket: 'sih-weighing-verification.firebasestorage.app',
    iosBundleId: 'com.example.ownerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4_Gd-cIa21JQUSHGJlN5CZnIIQ_2oFzQ',
    appId: '1:950594753791:web:4266a1251d7b8b280428ca',
    messagingSenderId: '950594753791',
    projectId: 'sih-weighing-verification',
    authDomain: 'sih-weighing-verification.firebaseapp.com',
    storageBucket: 'sih-weighing-verification.firebasestorage.app',
    measurementId: 'G-ZVM8RMQBNF',
  );
}
